from config import *








def zkhrafa(message):
		kok = message.text.lower()
		s = kok
		s = s.replace('a', '𝐴')
		s = s.replace('b', 'b')
		s = s.replace('c', '𝐶')
		s = s.replace('d', '𝐷')
		s = s.replace('e', '𝐸')
		s = s.replace('f', '𝐹')
		s = s.replace('g', '𝐺')
		s = s.replace('h', '𝐻')
		s = s.replace('i', '𝐼')
		s = s.replace('j', '𝐽')
		s = s.replace('k', '𝐾')
		s = s.replace('l', '𝐿')
		s = s.replace('m', '𝑀')
		s = s.replace('n', '𝑁')
		s = s.replace('o', '𝑂')
		s = s.replace('p', '𝑃')
		s = s.replace('q', '𝑄')
		s = s.replace('r', '𝑅')
		s = s.replace('s', '𝑆')
		s = s.replace('t', '𝑇')
		s = s.replace('u', '𝐔')
		s = s.replace('v', '𝑉')
		s = s.replace('w', '𝑊')
		s = s.replace('s', '𝑋')
		s = s.replace('y', '𝑌')
		s = s.replace('z', '𝑍')
		bot.send_message(message.chat.id, f"`{s}`",parse_mode = 'Markdown')
		
		a = kok
		a=a.replace('a','𝐀')
		a=a.replace('b','𝐁')
		a=a.replace('c','𝐂')
		a=a.replace('d','𝐃')
		a=a.replace('e','𝐄')
		a=a.replace('f','𝐅')
		a=a.replace('g','𝐆')
		a=a.replace('h','𝐇')
		a=a.replace('i','𝐈')
		a=a.replace('j','𝐉')
		a=a.replace('k','𝐊')
		a=a.replace('l','𝐋')
		a=a.replace('m','𝐌')
		a=a.replace('n','𝐍')
		a=a.replace('o','𝐎')
		a=a.replace('p','𝐏')
		a=a.replace('q','𝐐')
		a=a.replace('r','𝐑')
		a=a.replace('s','𝐒')
		a=a.replace('t','𝐓')
		a=a.replace('u','𝐔')
		a=a.replace('v','𝐕')
		a=a.replace('w','𝐖')
		a=a.replace('x','𝐗')
		a=a.replace('y','𝐘')
		a=a.replace('z','𝐙')
		bot.send_message(message.chat.id, f"`{a}`",parse_mode = 'Markdown')
		
		b=kok
		
		b=b.replace('a','𝖆')
		b=b.replace('b','𝖇')
		b=b.replace('c','𝖈')
		b=b.replace('d','𝖉')
		b=b.replace('e','𝖊')
		b=b.replace('f','𝖋')
		b=b.replace('g','𝖌')
		b=b.replace('h','𝖍')
		b=b.replace('i','𝖎')
		b=b.replace('j','𝖏')
		b=b.replace('k','𝖐')
		b=b.replace('l','𝖑')
		b=b.replace('m','𝖒')
		b=b.replace('n','𝖓')
		b=b.replace('o','𝖔')
		b=b.replace('p','𝖕')
		b=b.replace('q','𝖖')
		b=b.replace('r','𝖗')
		b=b.replace('s','𝖘')
		b=b.replace('t','𝖙')
		b=b.replace('u','𝖚')
		b=b.replace('v','𝖛')
		b=b.replace('w','𝖜')
		b=b.replace('x','𝖝')
		b=b.replace('y','𝖞')
		b=b.replace('z','𝖟')
		bot.send_message(message.chat.id, f"`{b}`",parse_mode = 'Markdown')
		
		c = kok
		c=c.replace('a','ᴬ')
		c=c.replace('b','ᴮ')
		c=c.replace('c','ᶜ')
		c=c.replace('d','ᴰ')
		c=c.replace('e','ᴱ')
		c=c.replace('f','ᶠ')
		c=c.replace('g','ᴳ')
		c=c.replace('h','ᴴ')
		c=c.replace('i','ᴵ')
		c=c.replace('j','ᴶ')
		c=c.replace('k','ᴷ')
		c=c.replace('l','ᴸ')
		c=c.replace('m','ᴹ')
		c=c.replace('n','ᴺ')
		c=c.replace('o','ᴼ')
		c=c.replace('p','ᴾ')
		c=c.replace('q','ᵟ')
		c=c.replace('r','ᴿ')
		c=c.replace('s','ˢ')
		c=c.replace('t','ᵀ')
		c=c.replace('u','ᵿ')
		c=c.replace('v','ᵛ')
		c=c.replace('w','ᵂ')
		c=c.replace('x','ˣ')
		c=c.replace('y','ᵞ')
		c=c.replace('z','ᶻ')
		bot.send_message(message.chat.id, f"`{c}`",parse_mode = 'Markdown')
		
		d=kok
		d=d.replace('a','𝓐')
		d=d.replace('b','𝓑')
		d=d.replace('c','𝓒')
		d=d.replace('d','𝓓')
		d=d.replace('e','𝓔')
		d=d.replace('f','𝓕')
		d=d.replace('g','𝓖')
		d=d.replace('h','𝓗')
		d=d.replace('i','𝓘')
		d=d.replace('j','𝓙')
		d=d.replace('k','𝓚')
		d=d.replace('l','𝓛')
		d=d.replace('m','𝓜')
		d=d.replace('n','𝓝')
		d=d.replace('o','𝓞')
		d=d.replace('p','𝓟')
		d=d.replace('q','𝓠')
		d=d.replace('r','𝓡')
		d=d.replace('s','𝕾')
		d=d.replace('t','𝓣')
		d=d.replace('u','𝓤')
		d=d.replace('v','𝓥')
		d=d.replace('w','𝓦')
		d=d.replace('x','𝓧')
		d=d.replace('y','𝓨')
		d=d.replace('z','𝓩')
		bot.send_message(message.chat.id, f"`{d}`",parse_mode = 'Markdown')
		
		e=kok
		e=e.replace('a','𝗔')
		e=e.replace('b','𝗕')
		e=e.replace('c','𝗖')
		e=e.replace('d','𝗗')
		e=e.replace('e','𝗘')
		e=e.replace('f','𝗙')
		e=e.replace('g','𝗚')
		e=e.replace('h','𝗛')
		e=e.replace('i','𝗜')
		e=e.replace('j','𝗝')
		e=e.replace('k','𝗞')
		e=e.replace('l','𝗟')
		e=e.replace('m','𝗠')
		e=e.replace('n','𝗡')
		e=e.replace('o','𝗢')
		e=e.replace('p','𝗣')
		e=e.replace('q','𝗤')
		e=e.replace('r','𝗥')
		e=e.replace('s','𝗦')
		e=e.replace('t','𝗧')
		e=e.replace('u','𝗨')
		e=e.replace('v','𝗩')
		e=e.replace('w','𝗪')
		e=e.replace('x','𝗫')
		e=e.replace('y','𝗬')
		e=e.replace('z','𝗭')
		bot.send_message(message.chat.id, f"`{e}`",parse_mode = 'Markdown')
		
		f=kok
		f=f.replace('a','𝑎')
		f=f.replace('b','𝑏')
		f=f.replace('c','𝑐')
		f=f.replace('d','𝑑')
		f=f.replace('e','𝑒')
		f=f.replace('f','𝑓')
		f=f.replace('g','𝑔')
		f=f.replace('h','ℎ')
		f=f.replace('i','𝑖')
		f=f.replace('j','𝑗')
		f=f.replace('k','𝑘')
		f=f.replace('l','𝑙')
		f=f.replace('m','𝑚')
		f=f.replace('n','𝑛')
		f=f.replace('o','𝑜')
		f=f.replace('p','𝑝')
		f=f.replace('q','𝑞')
		f=f.replace('r','𝑟')
		f=f.replace('s','𝑠')
		f=f.replace('t','𝑡')
		f=f.replace('u','𝑢')
		f=f.replace('v','𝑣')
		f=f.replace('w','𝑤')
		f=f.replace('x','𝑥')
		f=f.replace('y','𝑦')
		f=f.replace('z','𝑧')
		bot.send_message(message.chat.id, f"`{f}`",parse_mode = 'Markdown')
		
		g=kok
		g=g.replace('a','𝒂')
		g=g.replace('b','𝒃')
		g=g.replace('c','𝒄')
		g=g.replace('d','𝒅')
		g=g.replace('e','𝒆')
		g=g.replace('f','𝒇')
		g=g.replace('g','𝒈')
		g=g.replace('h','𝒉')
		g=g.replace('i','𝒊')
		g=g.replace('j','𝒋')
		g=g.replace('k','𝒌')
		g=g.replace('l','𝒍')
		g=g.replace('m','𝒎')
		g=g.replace('n','𝒏')
		g=g.replace('o','𝒐')
		g=g.replace('p','𝒑')
		g=g.replace('q','𝒒')
		g=g.replace('r','𝒓')
		g=g.replace('s','𝒔')
		g=g.replace('t','𝒕')
		g=g.replace('u','𝒖')
		g=g.replace('v','𝒗')
		g=g.replace('w','𝒘')
		g=g.replace('x','𝒙')
		g=g.replace('y','𝒚')
		g=g.replace('z','𝒛')
		bot.send_message(message.chat.id, f"`{g}`",parse_mode = 'Markdown')
		
		h=kok
		h=h.replace('a','𝙰')
		h=h.replace('b','𝙱')
		h=h.replace('c','𝙲')
		h=h.replace('d','𝙳')
		h=h.replace('e','𝙴')
		h=h.replace('f','𝙵')
		h=h.replace('g','𝙶')
		h=h.replace('h','𝙷')
		h=h.replace('i','𝙸')
		h=h.replace('j','𝙹')
		h=h.replace('k','𝙺')
		h=h.replace('l','𝙻')
		h=h.replace('m','𝙼')
		h=h.replace('n','𝙽')
		h=h.replace('o','𝙾')
		h=h.replace('p','𝙿')
		h=h.replace('q','𝚀')
		h=h.replace('r','𝚁')
		h=h.replace('s','𝚂')
		h=h.replace('t','𝚃')
		h=h.replace('u','𝙺')
		h=h.replace('v','𝚅')
		h=h.replace('w','𝚆')
		h=h.replace('x','𝚇')
		h=h.replace('y','𝚈')
		h=h.replace('z','𝚉')
		again=types.InlineKeyboardMarkup()
		ba=types.InlineKeyboardButton('-AGAIN-',callback_data='again')
		back=types.InlineKeyboardButton(text='MENU',callback_data='backma')
		again.row_width=2
		again.add(ba,back)
		bot.send_message(message.chat.id, f"`{h}`",parse_mode = 'Markdown',reply_markup=again)


def done_txt(message):
	mesgg = bot.send_message(message.chat.id, text='*SEND YOU\'R TEXT :*', parse_mode='Markdown')
	bot.register_next_step_handler(mesgg, zkhrafa)
	

